Add missing executableName for Linux platform
Fixes Electron Forge error in Linux (Debian):

An unhandled rejection has occurred inside Forge:
Error: could not find the Electron app binary at "/home/unknown/Apps/borderless/out/Borderless-linux-x64/borderless". You may need to re-bundle the app using Electron Packager's "executableName" option.